authorization_workgroup_names:
  rialto: 'sul:rialto'

email_suffix: '@stanford.edu'

# connected app config
tableau:
  base_url: https://tableau-uat.stanford.edu
  dashboard_base_path: '/#/site/DLSS/views/'
  # actual secrets are in vault and set by puppet
  client_id: STAGE_CLIENT_ID_HERE
  client_secret_id: STAGE_CLIENT_SECRET_ID_HERE
  client_secret_value: STAGE_CLIENT_SECRET_VALUE_HERE
  token_expiry_time_seconds: 600

dashboard:
  help_url: 'https://docs.google.com/document/d/1LohYMtb_AZfTUFDEzovYB0zo-5JBw5i9B8iZSt1feAM/edit?tab=t.0#heading=h.vh65hbsggtq4'

tabs:
  open_access:
    stanford-overview: Stanford Overview
    school-overview: School Overview
    school-details: School Details
    department-details: Department Details
  orcid_adoption:
    stanford-overview: Stanford Overview
    department-details: Department Details
    researcher-details: Researcher Details
  publications:
    stanford-overview: Stanford Overview
    type-overview: Type Overview
    school-details: School Details
    department-details: Department Details
